import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "Política de privacidad", description: "Política de privacidad de HerramientasCR.", alternates: { canonical: "/privacidad" } };

export default function Page() {
  return <div className="container page legal-page"><Breadcrumbs items={[{ label: "Privacidad" }]} /><article className="content-card longform"><h1>Política de privacidad</h1><p className="article-meta">Última actualización: 22 de septiembre de 2026</p><p>Esta política describe de forma general cómo HerramientasCR trata información al utilizar el sitio. El texto deberá revisarse nuevamente antes del lanzamiento oficial, cuando se definan dominio, responsable y herramientas externas definitivas.</p><h2>1. Datos ingresados en las calculadoras</h2><p>Las calculadoras están diseñadas para procesar los valores introducidos directamente en tu navegador. No necesitas crear una cuenta para utilizarlas y no debes introducir información personal sensible que no sea necesaria para el cálculo.</p><h2>2. Datos técnicos del alojamiento</h2><p>El proveedor de alojamiento puede procesar registros técnicos necesarios para entregar y proteger el servicio, por ejemplo dirección IP, solicitudes, errores, navegador y datos de seguridad.</p><h2>3. Analítica</h2><p>Google Analytics solo se carga si existe un identificador configurado y el usuario acepta la analítica mediante el control mostrado por el sitio. La configuración puede cambiar antes del lanzamiento.</p><h2>4. Publicidad</h2><p>El proyecto está preparado para integrar Google AdSense, pero permanece desactivado hasta configurar una cuenta, identificadores reales y los mecanismos de consentimiento exigibles. Cuando AdSense esté activo, proveedores externos, incluido Google, pueden usar cookies para mostrar anuncios según visitas a este sitio u otros sitios. Las cookies publicitarias de Google permiten a Google y sus socios mostrar y medir anuncios; los usuarios pueden gestionar la personalización de anuncios desde la configuración de anuncios de Google.</p><h2>5. Proveedores de terceros</h2><p>Los enlaces a instituciones y servicios externos se rigen por sus propias políticas. HerramientasCR no controla esos sitios.</p><h2>6. Contacto</h2><p>{siteConfig.contactConfigured ? <>Para consultas de privacidad puedes escribir a <a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a>.</> : <>El correo oficial de privacidad está pendiente de configuración antes del lanzamiento.</>}</p></article></div>;
}
