import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ConsentSettingsButton } from "@/components/ConsentManager";

export const metadata: Metadata = { title: "Política de cookies", description: "Información sobre cookies, consentimiento y almacenamiento local en HerramientasCR.", alternates: { canonical: "/cookies" } };

export default function Page() {
  return <div className="container page legal-page"><Breadcrumbs items={[{ label: "Cookies" }]} /><article className="content-card longform"><h1>Política de cookies</h1><p className="article-meta">Última actualización: 22 de septiembre de 2026</p><p>HerramientasCR puede utilizar almacenamiento local, cookies y tecnologías similares para recordar preferencias, medir el uso del sitio y, cuando se active oficialmente, mostrar publicidad.</p><h2>Cookies y almacenamiento necesarios</h2><p>El sitio puede guardar preferencias estrictamente necesarias para recordar elecciones de privacidad y mantener una experiencia consistente. Las calculadoras funcionan sin crear una cuenta.</p><h2>Analítica</h2><p>Google Analytics permanecerá desactivado hasta que exista un identificador de medición configurado y el usuario haya aceptado la categoría de analítica.</p><h2>Publicidad</h2><p>Google AdSense permanece desactivado durante esta etapa. Los espacios publicitarios visibles son únicamente vistas previas de ubicación. Cuando AdSense sea aprobado, las tecnologías publicitarias se cargarán únicamente según la configuración de consentimiento aplicable.</p><h2>CMP para Google</h2><p>Además de las preferencias internas del sitio, antes de servir anuncios personalizados a usuarios del Espacio Económico Europeo, Reino Unido o Suiza se configurará una CMP certificada por Google integrada con el Transparency &amp; Consent Framework (TCF) de IAB. Esa configuración se completará desde la cuenta de AdSense cuando esté disponible.</p><h2>Cambiar tus preferencias</h2><p>Puedes volver a abrir el panel de privacidad en cualquier momento.</p><p><ConsentSettingsButton /></p><h2>Control desde el navegador</h2><p>También puedes eliminar o bloquear cookies y almacenamiento desde la configuración del navegador. Si eliminas los datos del sitio, HerramientasCR volverá a solicitar tus preferencias.</p></article></div>;
}
